rly_file = "Manchester-Area.rly"
ttb_files = "Manchester-Area.ttb"
img_files = "Manchester-Area.jpg"
doc_files = ["README.md","A Brief History of Manchester Railways.pdf","Manchester Area operational notes.pdf","Manchester-Area log.txt"]
ssn_files = "Manchester Area - starting session.ssn"
release_date = "2024-01-25"
version = "1.0.0"
country_code = "GB"
factual = true
description = "A simulation of railways in the Manchester area"
year = 2024
display_name = "Manchester Area"
name = "Manchester Area"
signal_position = "left"
author = "RailOSDevTeam"
contributors = "Albert"
